name: chemprop
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pytorch>=2.1
  - astartes
  - aimsim
  - configargparse
  - lightning>=2.0
  - numpy
  - pandas
  - rdkit-dev
  - libboost-devel
  - cppyy
  - scikit-learn
  - scipy
  - rich
  - descriptastorus
